# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de5740fb9a0c25fd9c7fb480d99cc83837f533f655ff175a09b7e8dd84b6440e9619340a75eef3eb81a0d0acbb7f0ef503f156614f0c252786426801c8d6849e

test:
  secret_key_base: 76257b970ca98fedd6ea9ab6777acb24ccf85bc7fba950ae4f5192c88b89e2e3cc9cccaf93a15070d43c5ce2de30c33560faa8d3dab3c18266ca5c5e7330573c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
